CREATE TABLE BATCH_JOB (
  JOB_NAME              VARCHAR2(500)      NOT NULL,
  JOB_NAME_KR           VARCHAR2(500)      NOT NULL,
  APPLICATION           VARCHAR2(500)      NOT NULL,
  ENABLED               NUMBER(1)          NOT NULL,
  JOB_PERIOD            VARCHAR2(500)      NOT NULL,
  SORT_ORDER            NUMBER(10)         NOT NULL,
  CRON_EXPRESSION       VARCHAR2(500)          NULL,
  JOB_TYPE             VARCHAR2(500)          NULL,
  DESCRIPTION           VARCHAR2(4000)         NULL,
  DEV_ALERT             VARCHAR2(500)          NULL
);

COMMENT ON COLUMN BATCH_JOB.JOB_PERIOD IS '주기';
COMMENT ON COLUMN BATCH_JOB.JOB_TYPE IS  '업무유형';
COMMENT ON COLUMN BATCH_JOB.DEV_ALERT IS '예외발생시 연락할 개발자';
ALTER TABLE BATCH_JOB ADD ( PRIMARY KEY ( JOB_NAME ) USING INDEX        );

CREATE TABLE BATCH_STEP (
  STEP_NAME       VARCHAR2(100)      NOT NULL,
  STEP_NAME_KR    VARCHAR2(1000)     NOT NULL,
  DESCRIPTION     VARCHAR2(4000)         NULL
);

ALTER TABLE BATCH_STEP ADD ( CONSTRAINT PK_STEP_STATUS PRIMARY KEY ( STEP_NAME )         );

CREATE TABLE JOB_STEP_STATUS (
  JOB_NAME      VARCHAR2(100)     NOT NULL,
  STEP_NAME     VARCHAR2(100)     NOT NULL,
  SORT_ORDER    NUMBER(10)        NOT NULL
);

ALTER TABLE JOB_STEP_STATUS ADD ( CONSTRAINT PK_JOB_STEP_STATUS PRIMARY KEY ( JOB_NAME, SORT_ORDER )     );
